### ISSUE TITLE
此项目是否涉及过度宣传？

### ISSUE THREAD

**Issue by actuallyidk** [adysec/cf-mirror#1]
README 中以镜像源和中国大陆访问官方源的速度起手，然后你反手就上了 cloudflare 减速器，使用 Cloudflare Workers 反代了官方源，这是我使用长三角某地电信的直连速度。

![image](https://github.com/adysec/cf-mirror/assets/164127584/0533169e-c667-4809-8b04-77c3b99845c4)

> 仅做官方源的转发，给官方源加一层cdn

不少发行版（诸如 Debian 和 NixOS）官方镜像是有国际大厂提供除中国大陆外的全球 cdn 加速的，不加 cloudflare workers 反代的访问速度反而更快。

> 第三方源相对官方源软件版本更低，维护者也可能会夹带私货，洁癖患者难以忍受。

然后你反手就在 archlinux、archlinuxarm、centos、manjaro 等发行版反代起了镜像站

> 同时缓存静态内容加速，减少网络延迟和下载速度。

cloudflare workers 本身不带有缓存功能，如果使用 dns 解析那里的 cdn 功能，我对 cloudflare 是否会缓存大文件打上一个问号，再对使用 cloudflare cdn 分发非网站资源的行为是否违反 cloudflare 的 EULA 打上一个问号。

README 讲了很多，但似乎项目的实际使用场景仅仅局限于要用的这个发行版实在是太穷，官方源根本没有上 cdn ，而使用镜像的机子又恰好在境外的场景下使用。那我为什么不用一个 cloudflare workers 实现的万能反代服务呢？比如 https://github.com/netptop/siteproxy ，只需要在官方源前面加上一串自己的域名就好。

**Comment by adysec** [comment]
readme朋友随手帮写的，这个是个人用的站，没有做过宣传，仅在小范围使用，目前只用的上极个别源的代理，我了解到github有很多好的代理站项目，但目前对于个人而已已经足够使用了，正确的用法是根据worker.js调整出适合自己的私有化部署方案，感谢您的反馈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月11日(周六) 凌晨0:32
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [adysec/cf-mirror] 此项目是否涉及过度宣传？ (Issue #1)




 
README 中以镜像源和中国大陆访问官方源的速度起手，然后你反手就上了 cloudflare 减速器，使用 Cloudflare Workers 反代了官方源，这是我使用长三角某地电信的直连速度。
 
image.png (view on web)
  
仅做官方源的转发，给官方源加一层cdn
  
不少发行版（诸如 Debian 和 NixOS）官方镜像是有国际大厂提供除中国大陆外的全球 cdn 加速的，不加 cloudflare workers 反代的访问速度反而更快。
  
第三方源相对官方源软件版本更低，维护者也可能会夹带私货，洁癖患者难以忍受。
  
然后你反手就在 archlinux、archlinuxarm、centos、manjaro 等发行版反代起了镜像站
  
同时缓存静态内容加速，减少网络延迟和下载速度。
  
cloudflare workers 本身不带有缓存功能，如果使用 dns 解析那里的 cdn 功能，我对 cloudflare 是否会缓存大文件打上一个问号，再对使用 cloudflare cdn 分发非网站资源的行为是否违反 cloudflare 的 EULA 打上一个问号。
 
README 讲了很多，但似乎项目的实际使用场景仅仅局限于要用的这个发行版实在是太穷，官方源根本没有上 cdn ，而使用镜像的机子又恰好在境外的场景下使用。那我为什么不用一个 cloudflare workers 实现的万能反代服务呢？比如 https://github.com/netptop/siteproxy ，只需要在官方源前面加上一串自己的域名就好。

**Comment by adysec** [comment]
我会通过邮件联系cloudflare官方询问是否合规，感谢您的反馈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月11日(周六) 凌晨0:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [adysec/cf-mirror] 此项目是否涉及过度宣传？ (Issue #1)




  
使用 cloudflare cdn 分发非网站资源的行为是否违反 cloudflare 的 EULA 打上一个问号。
  
经过我又一番调查，cloudflare 在 2023 年 5 月废除了用户协议的 2.8 条，不再通过判断是否是非网站资源来对 cdn 使用进行限制。但在他们的这篇关于废除 2.8 条款的博客中明确写道:
  
Video and large files hosted outside of Cloudflare will still be restricted on our CDN, but we think that our service features, generous free tier, and competitive pricing
  
这并不意味着使用 cdn 分发大文件就不会受到 cloudflare 的限制，他们只是为了方便那些在使用 cloudflare R2 等产品的用户使用 cdn 分发资源，非 cloudflare 托管的大文件依然会受到限制。
