### ISSUE TITLE
如果我需要自己在cf上部署一样的workers有办法吗这样可以不抢占你的请求数

### ISSUE THREAD

**Issue by qjds** [adysec/cf-mirror#2]

**Comment by adysec** [comment]
可以的，这其实是最推荐的方式，也是我开源到github上的原因，worker.js和docker.js分别需要一个worker，其中docker.js中需要修改域名部分（worker可以配置多个域名，通过host判断请求转发到的容器镜像源），worker.js无需过多配置，如果需要帮助请随时通过issus或邮箱联系

**Comment by qjds** [comment]
我在群晖上使用docker套件发现一只是失败是失效了吗

**Comment by qjds** [comment]
我将代码复制到works后修改route为我分配的域名部署后docker在pull的时候一直失败

**Comment by adysec** [comment]
代码中的域名也需要改成对应的你分配的域名
